### ISSUE TITLE
Swapping pause/play buttons

### ISSUE THREAD

**Issue by Aadesh001** [maoiscat/mpv-osc-modern#15]
Hi there!
Sorry I'm not familiar with lua scripts. Your theme is awesome.
Except when the media is playing, the pause button is set to 'play', and when the media is paused, it shows 'pause'.
I don't know if it is intentional or not, but can you tell me which parameters to edit to swap these buttons?
Thank you.

**Comment by maoiscat** [comment]
line 1212 yes -> no



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 07/11/2022 21:00 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-modern] Swapping pause/play buttons (Issue #15) |

Hi there!
Sorry I'm not familiar with lua scripts. Your theme is awesome.
Except when the media is playing, the pause button is set to 'play', and when the media is paused, it shows 'pause'.
I don't know if it is intentional or not, but can you tell me which parameters to edit to swap these buttons?
Thank you.
