### ISSUE TITLE
How do you convert the icons in the file

### ISSUE THREAD

**Issue by Qiyue0726** [maoiscat/mpv-osc-modern#37]
The file opens with something like `play = '\239\142\170'`, I opened the file using vs code, how do I know its original icon?

**Comment by maoiscat** [comment]
you know texts start with '\' are escape characters, which are used since cant type it directly.




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月25日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maoiscat/mpv-osc-modern] How do you convert the icons in the file (Issue #37) |

The file opens with something like play = '\239\142\170', I opened the file using vs code, how do I know its original icon?

**Comment by maoiscat** [comment]
to see the icon character, check it in the font file



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月25日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [maoiscat/mpv-osc-modern] How do you convert the icons in the file (Issue #37) |

The file opens with something like play = '\239\142\170', I opened the file using vs code, how do I know its original icon?

**Comment by Qiyue0726** [comment]
I got, thanks
