### ISSUE TITLE
Material icon font won't load 

### ISSUE THREAD

**Issue by DrakoDom** [maoiscat/mpv-osc-modern#45]
Upon opening a video in mpv, I can see the following output in my terminal:
```
[osd/libass] fontselect: Using default font family: (mpv-osd-symbols, 400, 0) -> /usr/share/fonts/ubuntu-font-family/UbuntuMono-R.ttf, 0, UbuntuMono-Regular
[osd/libass] fontselect: Using default font family: (material-design-iconic-font, 400, 0) -> /usr/share/fonts/ubuntu-font-family/UbuntuMono-R.ttf, 0, UbuntuMono-Regular
```
Deleting `.config/fontconfig/fonts.conf` only changes `Ubuntu` to the `Liberation` font in the mpv output, and doesn't help with loading the Material font.

I have the `Material-Design-Iconic-Font.ttf` file installed in my `/usr/share/fonts/` folder.

Here's what icons look like right now inside mpv:

![scrot-2023-05-22_1684802504s](https://github.com/maoiscat/mpv-osc-modern/assets/79945730/9f277b33-f546-4d07-a8c4-b4e3a7bfabe4)

**Comment by maoiscat** [comment]
since i dont have a linux platform, please check mpv manual for solutions.

https://mpv.io/manual/master/#files



---- Replied Message ----
| From | Dominic ***@***.***> |
| Date | 05/23/2023 08:46 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-osc-modern] Material icon font won't load (Issue #45) |

Upon opening a video in mpv, I can see the following output in my terminal:

[osd/libass] fontselect: Using default font family: (mpv-osd-symbols, 400, 0) -> /usr/share/fonts/ubuntu-font-family/UbuntuMono-R.ttf, 0, UbuntuMono-Regular
[osd/libass] fontselect: Using default font family: (material-design-iconic-font, 400, 0) -> /usr/share/fonts/ubuntu-font-family/UbuntuMono-R.ttf, 0, UbuntuMono-Regular


Deleting .config/fontconfig/fonts.conf only changes Ubuntu to the Liberation font in the mpv output, and doesn't help with loading the Material font.

I have the Material-Design-Iconic-Font.ttf file installed in my /usr/share/fonts/ folder.

Here's what icons look like right now inside mpv:

**Comment by DrakoDom** [comment]
Wow. I feel silly. I was supposed to put the font in my mpv font folder. Not my system's font folder. Though, that didn't fix the issue.

I tried the [ModernX](https://github.com/cyl0/ModernX) fork, and it did load icons properly. I can't explain why.

![scrot-2023-05-23_1684851242s](https://github.com/maoiscat/mpv-osc-modern/assets/79945730/a6602ef9-3312-406b-846f-a91baebdf5a0)

**Comment by hooke007** [comment]
Because sth like `\xEF\x8E\xA0` is not supported, use decimal ones instead.
